apiVersion: apps/v1
kind: Deployment
metadata:
  name: gavinapp01
spec:
  selector:
    matchLabels:
      app: gavinapp01
  template:
    metadata:
      labels:
        app: gavinapp01
    spec:
      containers:
      - name: gavinapp01
        image: sbacr02.azurecr.io/gavinapp01:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5178
